# Custom Language File for Launcher Customizer

[ejs.app]
title = "MineSy Client"

[ejs.landing]
mediaGitHubURL = "https://minesy.net"
mediaTwitterURL = "https://minesy.net/twitter"
mediaInstagramURL = "https://minesy.net/instagram"
mediaYouTubeURL = "https://minesy.net/youtube"
mediaDiscordURL = "https://discord.minesy.net"

[ejs.settings]
sourceGithubLink = "https://github.com/TnTVlogs/MineSy-Client"
supportLink = "https://github.com/TnTVlogs/MineSy-Client/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido al MineSy Client"
welcomeDescription = "Con este cliente podrás disfrutar de una experiencia totalmente única de Minecraft, además de disfrutar de uno de los mejores servidores actuales de Minecraft."
welcomeDescCTA = "© 2024 MineSy Network"
