# Custom Language File for Launcher Customizer

[ejs.app]
title = "MineSy Client"

[ejs.landing]
mediaGitHubURL = "https://github.com/TnTVlogs/MineSy-Client"
mediaTwitterURL = "https://twitter.minesy.net"
mediaInstagramURL = "https://instagram.minesy.net"
mediaYouTubeURL = "https://youtube.minesy.net"
mediaDiscordURL = "https://discord.minesy.net"

[ejs.settings]
sourceGithubLink = "https://github.com/TnTVlogs/MineSy-Client"
supportLink = "https://github.com/TnTVlogs/MineSy-Client/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido al MineSy Client"
welcomeDescription = "Con este cliente podrás disfrutar de una experiencia totalmente única de Minecraft, además de disfrutar de uno de los mejores servidores actuales de Minecraft."
welcomeDescCTA = "© 2024 MineSy Network"
