[ejs.landing]
updateAvailableTooltip = "Actualización Disponible"
usernamePlaceholder = "Nombre de Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Configuración"
urlTooltip = "minesy.net"
discordTooltip = "Discord invite"
youtubeTooltip = "@MineSyNetwork"
instagramTooltip = "@MineSyNetwork"
twitterTooltip = "@MineSyNTW"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;Esenciales"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "• Ningún Servidor Seleccionado"
launchDetails = "Por favor espera..."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Verificando Noticias..."
newsErrorFailedSpan = "Error al Cargar Noticias"
newsErrorRetryButton = "Intentar de Nuevo"
newsErrorNoneSpan = "No Hay Noticias"

[js.landing.discord]
loading = "Cargando..."
joining = "Jugando en play.minesy.net"
joined = "Explorando"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "INICIO DE SESIÓN OFFLINE"
loginEmailError = "* Tu nombre de usuario debe tener al menos 4 caracteres"
loginEmailPlaceholder = "Tu Nombre de Usuario"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://minecraft.net/es-es/password/forgot/"
loginForgotPasswordText = "¿olvidaste tu contraseña?"
loginRememberMeText = "¿recordarme?"
loginButtonText = "INICIAR SESIÓN"
loginNeedAccountLink = "https://minecraft.net/es-es/store/minecraft-java-edition/"
loginNeedAccountText = "¿Necesitas una cuenta?"
loginPasswordDisclaimer1 = "Tu contraseña se envía directamente a Mojang y nunca se almacena."
loginPasswordDisclaimer2 = "{appName} no está afiliado con Mojang AB, Minecraft o Microsoft."

[js.discord]
starting = "Iniciando el Cliente..."
waiting = "Esperando al Cliente..."
state = "Servidor: {shortId}"

[ejs.loginOptions]
loginOptionsTitle = "Opciones de inicio de sesión"
loginWithMicrosoft = "Iniciar sesión con Microsoft"
loginWithMojang = "Iniciar sesión Offline"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Seleccionar una cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuración"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Cliente"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Listo"
tabAccountHeaderText = "Configuración de la cuenta"
tabAccountHeaderDesc = "Agregar nuevas cuentas o gestionar las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Agregar cuenta de Microsoft"
mojangAccount = "Offline"
addMojangAccount = "+ Agregar cuenta Offline"
minecraftTabHeaderText = "Configuración de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resolución del Juego"
launchFullscreenTitle = "Iniciar en pantalla completa."
autoConnectTitle = "Conectar automáticamente al servidor al iniciar."
launchDetachedTitle = "Iniciar proceso de juego separado del cliente."
launchDetachedDesc = "Si el juego no está separado, cerrar el cliente también cerrará el juego."
tabModsHeaderText = "Configuración de Mods"
tabModsHeaderDesc = "Activar o desactivar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods Requeridos"
optionalMods = "Mods Opcionales"
dropinMods = "Mods Adicionales"
addMods = "Agregar Mods"
dropInDesc = "Arrastra tus mods del cliente aquí, por favor usa solo archivos .jar."
dropinRefreshNote = "(F5 para Refrescar)"
shaderpacks = "Packs de Shaders"
shaderpackDesc = "Activar o desactivar shaders. Ten en cuenta que los shaders solo funcionarán sin problemas en configuraciones potentes. Puedes agregar packs personalizados aquí."
selectShaderpack = "Seleccionar Pack de Shaders"
tabJavaHeaderText = "Configuración de Java"
tabJavaHeaderDesc = "Gestionar la configuración de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "La RAM mínima recomendada es de 3 gigabytes. Configurar los valores mínimos y máximos con el mismo valor puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar ejecutable de Java"
javaExecSelButtonText = "Seleccionar archivo"
javaExecDesc = "El ejecutable de Java se valida antes de iniciar el juego."
javaPathDesc = "La ruta debe terminar con {pathSuffix}."
jvmOptsTitle = "Opciones JVM adicionales"
jvmOptsDesc = "Opciones que se proporcionarán a la JVM en tiempo de ejecución. -Xms y -Xmx no deben incluirse."
launcherTabHeaderText = "Configuración del cliente"
launcherTabHeaderDesc = "Opciones relacionadas con el propio cliente."
allowPrereleaseTitle = "Permitir actualizaciones de Pre-Lanzamiento."
allowPrereleaseDesc = "Las actualizaciones de pre-lanzamiento incluyen nuevas características que pueden no haber sido completamente probadas o integradas. Esto siempre será cierto si estás utilizando una versión de pre-lanzamiento."
dataDirectoryTitle = "Directorio de datos"
selectDataDirectory = "Seleccionar directorio de datos"
chooseFolder = "Seleccionar carpeta"
dataDirectoryDesc = "Todos los archivos de juego y las instalaciones de Java locales se almacenarán en el directorio de datos. Las capturas de pantalla y las partidas guardadas se almacenan en la carpeta de instancia para la configuración del servidor correspondiente."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver información y notas de lanzamiento para la versión actual."
aboutTitle = "{appName}"
stableRelease = "Versión Estable"
versionText = "Versión "
sourceGithub = "Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola de Herramientas de Desarrollador"
releaseNotes = "Notas de lanzamiento"
changelog = "Registro de Cambios"
noReleaseNotes = "No hay notas de lanzamiento"
viewReleaseNotes = "Ver notas de lanzamiento en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del cliente"
launcherUpdatesHeaderDesc = "Descarga, instala y revisa las actualizaciones para el cliente."
checkForUpdates = "Buscar actualizaciones"
whatsNew = "¿Qué hay de nuevo?"
updateReleaseNotes = "Notas de lanzamiento de la actualización"

[ejs.waiting]
waitingText = "Esperando a Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.login]
login = "INICIAR SESIÓN"
loggingIn = "INICIANDO SESIÓN"
success = "ÉXITO"
tryAgain = "Intentar de Nuevo"

[js.index]
microsoftLoginTitle = "Microsoft Login"
microsoftLogoutTitle = "Microsoft Logout"

[js.login.error]
invalidValue = "* Tu nombre de usuario debe tener al menos 4 caracteres"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Error desconocido durante el Inicio de Sesión"
desc = "Se ha producido un error desconocido. Consulta nuestro discord para obtener más detalles."

[js.landing.launch]
pleaseWait = "Por favor espera..."
failureTitle = "Error durante el lanzamiento"
failureText = "Consulta nuestro discord para obtener más detalles."
okay = "Aceptar"

[js.landing.selectedAccount]
noAccountSelected = "Ninguna cuenta seleccionada"

[js.landing.selectedServer]
noSelection = "Ningún servidor seleccionado"
loading = "Cargando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Verificando información del sistema.."
noCompatibleJava = "No se Encontró una Instalación de Java Compatible"
installJavaMessage = "Para iniciar Minecraft, necesitas una instalación de Java de 64 bits {major}. ¿Te gustaría que instaláramos una copia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando Descarga de Java.."
javaDownloadFailureTitle = "Error Durante la Descarga de Java"
javaDownloadFailureText = "Consulta nuestro discord para obtener más detalles."
javaRequired = "Se Requiere Java para Iniciar"
javaRequiredMessage = 'Se requiere una instalación válida de Java {major} x64 para iniciar. Consulta nuestra <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guía de Gestión de Java</a> para obtener instrucciones sobre cómo instalar Java manualmente.'
javaRequiredDismiss = "Entiendo"
javaRequiredCancel = "Volver Atrás"

[js.landing.downloadJava]
findJdkFailure = "Error al encontrar la distribución de OpenJDK."
javaDownloadCorruptedError = "El JDK descargado tiene un hash incorrecto, el archivo puede estar corrupto."
extractingJava = "Extrayendo Java"
javaInstalled = "Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Cargando información del servidor.."
fatalError = "Error Fatal"
unableToLoadDistributionIndex = "No se pudo cargar una copia del índice de distribución. Consulta nuestro discord para obtener más detalles."
pleaseWait = "Por favor espera..."
errorDuringLaunchTitle = "Error Durante el Lanzamiento"
seeConsoleForDetails = "Consulta nuestro discord para obtener más detalles."
validatingFileIntegrity = "Validando integridad del archivo.."
errorDuringFileVerificationTitle = "Error Durante la Verificación del Archivo"
downloadingFiles = "Descargando archivos.."
errorDuringFileDownloadTitle = "Error Durante la Descarga del Archivo"
preparingToLaunch = "Preparando para lanzar.."
launchingGame = "Iniciando juego.."
launchWrapperNotDownloaded = "El archivo principal, LaunchWrapper, no se descargó correctamente. Como resultado, el juego no puede iniciarse. Para solucionar este problema, desactiva temporalmente tu software antivirus y vuelve a iniciar el juego. Si tienes tiempo, por favor <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">envía un problema</a> y háznoslo saber qué software antivirus usas. Nos pondremos en contacto con ellos e intentaremos solucionar las cosas."
doneEnjoyServer = "Listo. ¡Disfruta del juego!"
checkConsoleForDetails = "Consulta nuestro discord para obtener más detalles."

[js.landing.news]
checking = "Verificando Noticias"

[js.settings.fileSelectors]
executables = "Ejecutables"
allFiles = "Todos los Archivos"

[js.settings.mstfLogin]
errorTitle = "Algo Salió Mal"
errorMessage = "La autenticación de Microsoft falló. Por favor, inténtalo de nuevo."
okButton = "Aceptar"

[js.settings.mstfLogout]
errorTitle = "Algo Salió Mal"
errorMessage = "El cierre de sesión de Microsoft falló. Por favor, inténtalo de nuevo."
okButton = "Aceptar"

[js.settings.authAccountSelect]
selectButton = "Seleccionar Cuenta"
selectedButton = "Cuenta Seleccionada ✓"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Advertencia Esta es Tu Última Cuenta"
lastAccountWarningMessage = "Para usar el cliente debes estar conectado al menos a una cuenta. Deberás iniciar sesión nuevamente después. ¿Estás seguro de que deseas cerrar sesión?"
confirmButton = "Estoy Seguro"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nombre de Usuario"
uuid = "UUID"
selectAccount = "Seleccionar Cuenta"
selectedAccount = "Cuenta Seleccionada ✓"
logout = "Cerrar Sesión"

[js.settings.dropinMods]
removeButton = "Eliminar"
deleteFailedTitle = "Error al Eliminar Mod Adicional {fullName}"
deleteFailedMessage = "Asegúrate de que el archivo no esté en uso e inténtalo de nuevo."
failedToggleTitle = "Error al Alternar Uno o Más Mods Adicionales"
okButton = "Aceptar"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Seleccionado: Java {version} ({vendor})"
invalidSelection = "Selección Inválida"
requiresJava = "Requiere Java {major} x64."
availableOptions = "Opciones Disponibles para Java {major} (VM HotSpot)"

[js.settings.about]
preReleaseTitle = "Pre-lanzamiento"
stableReleaseTitle = "Versión Estable"
releaseNotesFailed = "Error al cargar las notas de lanzamiento."

[js.settings.updates]
newReleaseTitle = "Nueva Versión Disponible"
newPreReleaseTitle = "Nuevo Pre-lanzamiento Disponible"
downloadingButton = "Descargando.."
downloadButton = 'Descargar desde GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Cierra el cliente y ejecuta el dmg para actualizar.</span>'
latestVersionTitle = "Estás Ejecutando la Última Versión"
checkForUpdatesButton = "Buscar Actualizaciones"
checkingForUpdatesButton = "Buscando Actualizaciones.."

[js.uibinder.startup]
fatalErrorTitle = "Error Fatal: No se Pudo Cargar el Índice de Distribución"
fatalErrorMessage = "No se pudo establecer una conexión con nuestros servidores para descargar el índice de distribución. No había copias locales disponibles para cargar. <br><br>El índice de distribución es un archivo esencial que proporciona la última información del servidor. El cliente no puede iniciar sin él. Asegúrate de estar conectado a internet y vuelve a iniciar la aplicación."
closeButton = "Cerrar"

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.validateAccount]
failedMessageTitle = "Error al Actualizar el Inicio de Sesión"
failedMessage = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, selecciona otra cuenta o inicia sesión nuevamente."
failedMessageSelectAnotherAccount = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, inicia sesión nuevamente."
loginButton = "Iniciar Sesión"
selectAnotherAccountButton = "Seleccionar Otra Cuenta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando Actualizaciones..."
installNowButton = "Instalar Ahora"
checkForUpdatesButton = "Buscar Actualizaciones"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
